name: Deploy To gh-pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docs
        run: |
          yarn 
          yarn docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: packages/.vitepress/dist
